name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make all-hp
      run: make all-hp
    - name: make all-ht
      run: make all-ht
    - name: make all-sht
      run: make all-sht
    - name: make all-main
      run: make all-main
    - name: make all-stat
      run: make all-stat
